import os
import h5py
import numpy as np
import pandas as pd
import datetime
import math
from tqdm import tqdm
import multiprocessing
import joblib
import contextlib
from joblib import Parallel, delayed

import logging
# Suppress massive PyTorch/NeuralProphet logs per pixel
logging.getLogger("pytorch_lightning").setLevel(logging.ERROR)
logging.getLogger("NP").setLevel(logging.ERROR)
import warnings
warnings.filterwarnings('ignore')

from neuralprophet import NeuralProphet

@contextlib.contextmanager
def tqdm_joblib(tqdm_object):
    """Context manager to patch joblib to report into tqdm progress bar."""
    class TqdmBatchCompletionCallback(joblib.parallel.BatchCompletionCallBack):
        def __call__(self, *args, **kwargs):
            tqdm_object.update(n=self.batch_size)
            return super().__call__(*args, **kwargs)

    old_batch_callback = joblib.parallel.BatchCompletionCallBack
    joblib.parallel.BatchCompletionCallBack = TqdmBatchCompletionCallback
    try:
        yield tqdm_object
    finally:
        joblib.parallel.BatchCompletionCallBack = old_batch_callback
        tqdm_object.close()

# ==========================================
# 1. CONFIGURATION
# ==========================================
LOCATION = "Tait"
H5_PATH = f"C:/satelliteImagery/HLST30/HLST_{LOCATION}_Harmonized_SC_EM-7_Norm-None.h5"
TARGET_METRIC = 'sliding_volume_z_score'

# NeuralProphet specific parameters
MIN_SAMPLES = 50
N_CHANGEPOINTS = 5
TREND_REG = 1.5          # Lower = more flexible trend (more structural breaks), Higher = stiffer trend
SLOPE_CHANGE_THRESH = 0.02 # Threshold for identifying a trend changepoint
QUANTILES = [0.05, 0.95] # 90% confidence interval for transient anomalies
EVENT_GROUPING_DAYS = 30
MIN_CLUSTER_SIZE = 4     # Only flag events with at least this many sequential/grouped anomalies


def _process_row_chunk(chunk_args):
    import warnings
    import logging
    warnings.filterwarnings('ignore')
    logging.getLogger("pytorch_lightning").setLevel(logging.ERROR)
    logging.getLogger("NP").setLevel(logging.ERROR)

    (y_start, y_end, width, y_data, valid_mask, acq_times,
     min_samples, event_grouping_days, min_cluster_size, n_cp, trend_reg, slope_thresh, quantiles) = chunk_args

    num_frames = y_data.shape[0]
    chunk_height = y_end - y_start

    # Output arrays
    chunk_pred = np.full((num_frames, chunk_height, width), np.nan, dtype=np.float32)
    chunk_rmse = np.full((num_frames, chunk_height, width), np.nan, dtype=np.float32) # Using this for uncertainty band width
    chunk_flags = np.zeros((num_frames, chunk_height, width), dtype=np.uint8)
    chunk_date = np.full((chunk_height, width), np.nan, dtype=np.float64)
    chunk_count = np.zeros((chunk_height, width), dtype=np.int32)

    for y_local in range(chunk_height):
        y_global = y_start + y_local
        for x in range(width):
            pixel_valid = valid_mask[:, y_global, x]
            valid_indices = np.where(pixel_valid)[0]

            if len(valid_indices) < min_samples:
                continue

            # Extract valid signal and corresponding timestamps
            signal = y_data[valid_indices, y_global, x].astype(np.float64)
            signal_acq_times = acq_times[valid_indices]
            dates = pd.to_datetime(signal_acq_times, unit='s')
            
            df = pd.DataFrame({'ds': dates, 'y': signal})
            # Ensure chronological order and drop naive duplicates if any
            df = df.sort_values('ds').drop_duplicates('ds')
            
            if len(df) < min_samples:
                continue

            try:
                # 1. Initialize NeuralProphet with CUDA
                m = NeuralProphet(
                    yearly_seasonality=3, # Mathematically locked to 365.25 days with 3 Fourier orders
                    weekly_seasonality=False,
                    daily_seasonality=False,
                    n_changepoints=n_cp,
                    trend_reg=trend_reg,
                    quantiles=quantiles,
                    accelerator='gpu',
                    epochs=5, # Reduced to 10 for rapid first iteration
                    impute_missing=False, # Mathematically enforce raw data integrity
                    drop_missing=True,    # Discard the NaN rows generated by the daily resampling step
                    trainer_config={
                        "default_root_dir": "C:/satelliteImagery/HLST30/neuralProphet",
                        "enable_checkpointing": False
                    }
                )

                
                # Add sub-annual phenological cycles
                m.add_seasonality(name='cycle_180', period=180, fourier_order=2)
                m.add_seasonality(name='cycle_120', period=120, fourier_order=1)
                m.add_seasonality(name='cycle_90', period=90, fourier_order=1)
                
                # 2. Fit the model
                # Set learning_rate explicitly to skip the extremely slow LR finder per pixel
                m.fit(df, freq='D', progress=None, minimal=True, learning_rate=0.1)
                
                # 3. Predict to get trend, yhat, and quantiles
                forecast = m.predict(df)
                
                # Verify forecast length matches (should generally map 1:1 since we predict on training df)
                if len(forecast) != len(df):
                    continue
                    
                # 4. Extract Structural Shifts (Changepoints)
                trend = forecast['trend'].values
                # 1st deriv (slope)
                slopes = np.diff(trend)
                # 2nd deriv (slope changes)
                slope_changes = np.diff(slopes)
                # Find indices where slope change exceeds threshold.
                # slope_changes[i] is the change at index i+1
                struct_indices_df = np.where(np.abs(slope_changes) > slope_thresh)[0] + 1
                
                # 5. Extract Transient Shifts (Outside Quantiles)
                # Column names dynamically created based on quantiles
                col_low = f'yhat1 {quantiles[0]*100}%'
                col_high = f'yhat1 {quantiles[1]*100}%'
                
                # Fill na just in case, though they shouldn't be na
                is_transient = (df['y'].values > forecast[col_high].values) | (df['y'].values < forecast[col_low].values)
                transient_indices_df = np.where(is_transient)[0]
                
                # Combine both anomaly sets
                all_anom_df_indices = np.unique(np.concatenate([struct_indices_df, transient_indices_df]))
                
                if len(all_anom_df_indices) == 0:
                    pass
                else:
                    # 6. Group anomalies into events
                    events_ts = []
                    events_df_idx = []
                    current_event_ts = []
                    current_event_df_idx = []
                    
                    for df_idx in all_anom_df_indices:
                        ts = signal_acq_times[df_idx]
                        if not current_event_ts:
                            current_event_ts = [ts]
                            current_event_df_idx = [df_idx]
                        else:
                            last_ts = current_event_ts[-1]
                            if (ts - last_ts) <= (event_grouping_days * 86400):
                                current_event_ts.append(ts)
                                current_event_df_idx.append(df_idx)
                            else:
                                events_ts.append(current_event_ts)
                                events_df_idx.append(current_event_df_idx)
                                current_event_ts = [ts]
                                current_event_df_idx = [df_idx]
                    
                    if current_event_ts:
                        events_ts.append(current_event_ts)
                        events_df_idx.append(current_event_df_idx)
                        
                    # Filter events by minimum cluster size
                    valid_events_ts = []
                    valid_events_df_idx = []
                    
                    for ts_ev, idx_ev in zip(events_ts, events_df_idx):
                        if len(ts_ev) >= min_cluster_size:
                            valid_events_ts.append(ts_ev)
                            valid_events_df_idx.append(idx_ev)

                    # Now map back to original frame indices for valid clusters only
                    for idx_ev in valid_events_df_idx:
                        for df_idx in idx_ev:
                            frame_idx = valid_indices[df_idx]
                            chunk_flags[frame_idx, y_local, x] = 1
                        
                    change_count_val = len(valid_events_ts)
                    chunk_count[y_local, x] = change_count_val
                    
                    if change_count_val > 0:
                        chunk_date[y_local, x] = valid_events_ts[0][0]

                # Write predictions out
                # Write standard yhat to predicted_series
                for df_idx in range(len(forecast)):
                    frame_idx = valid_indices[df_idx]
                    chunk_pred[frame_idx, y_local, x] = forecast['yhat1'].values[df_idx]
                    # We'll store the uncertainty band width in RMSE
                    chunk_rmse[frame_idx, y_local, x] = forecast[col_high].values[df_idx] - forecast[col_low].values[df_idx]


            except Exception as e:
                # E.g. fitting errors
                pass

    return y_start, y_end, chunk_pred, chunk_rmse, chunk_flags, chunk_date, chunk_count


def main():
    import warnings
    warnings.filterwarnings('ignore')

    output_h5 = f"C:/satelliteImagery/HLST30/CCD/{LOCATION}_CCD_neuralprophet_Change_Detection_{TARGET_METRIC}.h5"

    print(f"Loading data from {H5_PATH}...")
    with h5py.File(H5_PATH, 'r') as f:
        data_grp = f['/HDFEOS/GRIDS/HARMONIZED/Data Fields']
        metric_ds = data_grp[TARGET_METRIC]

        acq_times = metric_ds.attrs['acquisition_time'][:]
        y_data = metric_ds[...]

        common_mask = data_grp['common_mask'][...]
        valid_mask = (common_mask == 0) & ~np.isnan(y_data)

        geo_transform = metric_ds.attrs.get('GeoTransform')
        spatial_ref = metric_ds.attrs.get('spatial_ref')

    num_frames, height, width = y_data.shape

    sort_idx = np.argsort(acq_times)
    acq_times = acq_times[sort_idx]
    y_data = y_data[sort_idx, ...]
    valid_mask = valid_mask[sort_idx, ...]

    print(f"Dataset shape: {num_frames} frames, {height}x{width} pixels")

    change_date_map = np.zeros((height, width), dtype=np.float64)
    change_date_map[:] = np.nan
    change_count_map = np.zeros((height, width), dtype=np.int32)

    predicted_series = np.full((num_frames, height, width), np.nan, dtype=np.float32)
    rmse_series = np.full((num_frames, height, width), np.nan, dtype=np.float32)
    anomaly_flags = np.zeros((num_frames, height, width), dtype=np.uint8)

    print(f"\nExecuting NeuralProphet detection (CUDA)...")

    # Due to PyTorch CUDA memory limitations and contexts, running 12 workers on GPU simultaneously
    # can crash depending on VRAM. Let's restrict to a safe number of concurrent workers (e.g., 4)
    n_jobs = min(8, multiprocessing.cpu_count())
    print(f"Using {n_jobs} cores for parallel processing.")

    num_chunks = max(1, n_jobs * 4)
    chunk_size = max(1, math.ceil(height / num_chunks))

    chunks = []
    for y_start in range(0, height, chunk_size):
        y_end = min(y_start + chunk_size, height)
        chunk_args = (
            y_start, y_end, width,
            y_data, valid_mask,
            acq_times,
            MIN_SAMPLES, EVENT_GROUPING_DAYS, MIN_CLUSTER_SIZE,
            N_CHANGEPOINTS, TREND_REG, SLOPE_CHANGE_THRESH, QUANTILES
        )
        chunks.append(chunk_args)

    # Use loky backend which is spawn-based and safer for PyTorch
    with tqdm_joblib(tqdm(desc="Processing row chunks", total=len(chunks))):
        results = Parallel(n_jobs=n_jobs, backend='loky')(
            delayed(_process_row_chunk)(chunk) for chunk in chunks
        )

    for y_start, y_end, c_pred, c_rmse, c_flags, c_date, c_count in results:
        predicted_series[:, y_start:y_end, :] = c_pred
        rmse_series[:, y_start:y_end, :] = c_rmse
        anomaly_flags[:, y_start:y_end, :] = c_flags
        change_date_map[y_start:y_end, :] = c_date
        change_count_map[y_start:y_end, :] = c_count

    os.makedirs(os.path.dirname(output_h5), exist_ok=True)
    print(f"\nSaving Results to {output_h5}...")
    with h5py.File(output_h5, 'w') as out_file:
        if spatial_ref is not None:
            out_file.attrs['spatial_ref'] = spatial_ref
        if geo_transform is not None:
            out_file.attrs['GeoTransform'] = geo_transform

        out_file.attrs['MIN_SAMPLES'] = MIN_SAMPLES
        out_file.attrs['TARGET_METRIC'] = TARGET_METRIC
        out_file.attrs['SOURCE_DATA'] = H5_PATH
        out_file.attrs['NP_N_CHANGEPOINTS'] = N_CHANGEPOINTS
        out_file.attrs['NP_TREND_REG'] = TREND_REG
        out_file.attrs['NP_SLOPE_CHANGE_THRESH'] = SLOPE_CHANGE_THRESH
        out_file.attrs['EVENT_GROUPING_DAYS'] = EVENT_GROUPING_DAYS

        out_file.create_dataset('predicted_series', data=predicted_series, compression='gzip')
        out_file.create_dataset('rmse_series', data=rmse_series, compression='gzip')
        out_file.create_dataset('anomaly_flags', data=anomaly_flags, compression='gzip')
        out_file.create_dataset('change_date_timestamp', data=change_date_map, compression='gzip')
        out_file.create_dataset('change_count', data=change_count_map, compression='gzip')

    print("NeuralProphet Pipeline Complete!")
    return output_h5

if __name__ == '__main__':
    main()
