locations:
  Rochesterv2:
    SOURCE_CACHE: null
    ROI_LON_MIN: -77.770166
    ROI_LON_MAX: -77.376776
    ROI_LAT_MIN: 42.961778
    ROI_LAT_MAX: 43.342135
    START_DATE: '2014-01-01'
    END_DATE: '2026-06-01'
    TANAGER_AVAILABLE: true
    TANAGER_STAC_URL: https://www.planet.com/data/stac/tanager-core-imagery/ROCX2025/collection.json
    DRAGONETTE_AVAILABLE: true
    DRAGONETTE_STAC_URL: https://wyvern-odp.com/industry/spatio_temporal/collection.json
  Tait:
    SOURCE_CACHE: Rochesterv2
    ROI_LON_MIN: -77.516127
    ROI_LON_MAX: -77.461968
    ROI_LAT_MIN: 43.127698
    ROI_LAT_MAX: 43.159168
    START_DATE: '2014-01-01'
    END_DATE: '2026-06-01'
    TANAGER_AVAILABLE: true
    TANAGER_STAC_URL: https://www.planet.com/data/stac/tanager-core-imagery/ROCX2025/collection.json
    DRAGONETTE_AVAILABLE: true
    DRAGONETTE_STAC_URL: https://wyvern-odp.com/industry/spatio_temporal/collection.json
  Guatemala-Debris:
    SOURCE_CACHE: null
    ROI_LON_MIN: -88.222
    ROI_LON_MAX: -87.822
    ROI_LAT_MIN: 15.6362
    ROI_LAT_MAX: 16.0362
    START_DATE: '2020-08-01'
    END_DATE: '2020-10-31'
    TANAGER_AVAILABLE: false
  MtEtna:
    SOURCE_CACHE: MtEtna-Catania
    ROI_LON_MIN: 14.91
    ROI_LON_MAX: 15.09
    ROI_LAT_MIN: 37.69
    ROI_LAT_MAX: 37.83
    START_DATE: '2020-08-01'
    END_DATE: '2021-07-31'
    TANAGER_AVAILABLE: false
  MtEtna-Catania:
    SOURCE_CACHE: MtEtna-Catania
    ROI_LON_MIN: 14.8
    ROI_LON_MAX: 15.35
    ROI_LAT_MIN: 37.4
    ROI_LAT_MAX: 37.9
    START_DATE: '2024-01-01'
    END_DATE: '2025-01-01'
    TANAGER_AVAILABLE: false
  BuenosAires:
    SOURCE_CACHE: BuenosAires
    ROI_LON_MIN: -58.79
    ROI_LON_MAX: -58.45
    ROI_LAT_MIN: -34.8
    ROI_LAT_MAX: -34.26
    START_DATE: '2025-01-01'
    END_DATE: '2026-01-01'
    TANAGER_AVAILABLE: true
    TANAGER_STAC_URL: https://www.planet.com/data/stac/tanager-core-imagery/urban/collection.json
  Palisades:
    SOURCE_CACHE: Palisades
    ROI_LON_MIN: -118.92
    ROI_LON_MAX: -118.375
    ROI_LAT_MIN: 33.9
    ROI_LAT_MAX: 34.85
    START_DATE: '2024-01-01'
    END_DATE: '2026-01-01'
    TANAGER_AVAILABLE: true
    TANAGER_STAC_URL: https://www.planet.com/data/stac/tanager-core-imagery/fire/collection.json
  Malibu:
    SOURCE_CACHE: Palisades
    ROI_LON_MIN: -118.777313
    ROI_LON_MAX: -118.486176
    ROI_LAT_MIN: 34.020795
    ROI_LAT_MAX: 34.169772
    START_DATE: '2015-01-01'
    END_DATE: '2026-01-01'
    TANAGER_AVAILABLE: true
    TANAGER_STAC_URL: https://www.planet.com/data/stac/tanager-core-imagery/fire/collection.json
    DRAGONETTE_AVAILABLE: false
    DRAGONETTE_STAC_URL: https://wyvern-odp.com/industry/spatio_temporal/collection.json
current_run:
  location: Malibu
